### ISSUE TITLE
cannot move any applets after adding screenshot applet

### ISSUE THREAD

**Issue by fossfreedom** [cybre/budgie-screenshot-applet#10]
Very odd thing happening on ubuntu 16.04

I've redone our budgie-remix deb package for v0.3.9.

After using raven and adding the applet, the applet appears in the middle of the panel - as expected.

However you lose all ability to move ANY applets.  You can only move applets again when you remove the newly added screenshot applet.

Any thoughts on this?

**Comment by cybre** [comment]
I can't reproduce this :/
Can you try with latest budgie-desktop from git and see if the problem exists?

**Comment by ikeydoherty** [comment]
Cannot reproduce here with git builds of budgie-desktop + budgie-screenshot-applet.
One assumes that the next releases will fix this...

**Comment by fossfreedom** [comment]
will revisit this in the coming days with v10.2.8 - @cybre I presume 0.3.9(.1) has the API applet change (change from gtkbin to gtkeventbox) ?  maybe that's my issue.

**Comment by fossfreedom** [comment]
rebuilt with 0.3.9.1 and all is well.  cheers.

**Comment by ikeydoherty** [comment]
Woot =) My assumption is also that it's related to the EventBox changes
