### ISSUE TITLE
Support Debian?

### ISSUE THREAD

**Issue by fossfreedom** [cybre/budgie-screenshot-applet#22]
Hi,

  I'm thinking of proposing this to Debian for Stretch + 1 - and hence will be sync'd to Ubuntu i.e. massive visible audience for your good work.

So a couple of questions.

Will you be strongly considering maintaining this applet for budgie-desktop v11 or is this applet only for budgie-desktop v10.x ?

Will you be willing to work with me to resolve the strict Debian packaging requirements? i.e. stuff like source copyright statements, copyright years correctly applied, all copyrights and licensing correctly attributed, PGP signing releases etc etc.?

**Comment by cybre** [comment]
Hi,

Firstly, sorry for the late reply; I was at school and that gave me some time to plan this out.

I am definitely interested in getting `budgie-screenshot-applet` into the Debian archives.
As you may know, the applet will have to be rewritten for Budgie 11 and I definitely want to do that.
The Budgie 11 port will be developed in a separate branch until the Budgie 11 APIs are stable and it gets adopted in Solus (and hopefully in Ubuntu Budgie). After this, the development on the Budgie 10.x version stops and the Budgie 11 branch gets merged into master.

I would appreciate if you gave me a short list of stuff I should be looking for so I could resolve the obvious stuff before the inclusion process starts. This will give me a bit of a headstart.

I also hold the right to terminate the process if I disagree with a required change and if there is no reasonable solution (I know it can get ridiculous). If it comes to this I want you to know that I have nothing against you or your team but the strict packaging requirements (and I really hope it doesn't come to this).

Edit: I now realized Stretch + 1 is due in 2019. By that time, Budgie 11 is going to be default for both distributions :)

**Comment by cybre** [comment]
Now that I think of it. Correct me if I'm wrong but if the Stretch + 1 soft freeze is in 2019 then we should probably start the process after the Budgie 11 port.

**Comment by fossfreedom** [comment]
understand. Actually, no harm in starting the process at anytime.  Updating to a newer version is much quicker once it is in the repositories.  Also, many people stay on the testing branch rather than on stable so they dont wait for 2019 or later. 

Anyway - having had a quick look and the sources are in very good shape. Well engineered - congrats!

1. All sources need your copyright changed from 2016 to "2016-2017"
2. like Ikey has done - PGP sign your releases - this is to ensure that the source is guaranteed to come directly from you and no-one else.
3. The translations - definitely GPL licensed or some-other license?  Transifex has no claim on the translations?
4. I just need a 3 line (max 80 chars per line) or more description that describes your applet.

That's it really - can't spot anything else that Debian would quibble with.

**Comment by cybre** [comment]
Is the complete rewrite in a completely different language/framework not going to trigger a re-review of the package?

**Comment by fossfreedom** [comment]
it will do - but certainly not the 1 - 3 month upload procedure.

**Comment by cybre** [comment]
Ah. Okay then. We can start the process sooner.

**Comment by cybre** [comment]
* I will change to copyright ranges.
* The next release will be PGP signed.
* Translations are GPL. Just like with Budgie, they're done by volunteers and Transifex holds no right to them.
* I will either come up with a description or ask someone to describe it otherwise the description could end up being a bit biased :)

I plan on doing the new release by the end of the week so that will be PGP signed.

**Comment by cybre** [comment]
I'll do the next release by the end of the week so we can start then. Sounds ok?

**Comment by fossfreedom** [comment]
perfect!

**Comment by cybre** [comment]
The copyright years have been changed in 9d13f1f

**Comment by fossfreedom** [comment]
will re-raise this after QT budgie-desktop v11.

**Comment by rawsh** [comment]
Ping?

**Comment by cybre** [comment]
@rawsh The issue has been closed. Why are you bumping it?
