### ISSUE TITLE
Custom upload location?

### ISSUE THREAD

**Issue by Danissl** [cybre/budgie-screenshot-applet#31]
Id just like to request the possibility to add our own hosting sites, in my case, puush.me. 

Thank you!

**Comment by cybre** [comment]
It's not as easy as that. Different services take different parameters. 
Besides, does puush.me even provide a REST API?

**Comment by cybre** [comment]
Closing as this is not something I want to do. I will consider adding any service users want as long as it doesn't require an account, has an API, and isn't full of ads.
