### ISSUE TITLE
Budgie 10.4 crashes when applet is added to panel

### ISSUE THREAD

**Issue by rodrigo-nogues** [cybre/budgie-screenshot-applet#32]
After Budgie was updated to 10.4, it is not possible to add applet to any panel. 

When trying to add the panel, Budgie settings freezes for a moment, then Budgie crashes, restart and the applet is not added.

This was not happening before 10.4.

**Comment by cybre** [comment]
Are you using the latest version of the applet?

**Comment by rodrigo-nogues** [comment]
I'm using v0.4.2-0.1, latest available in AUR, is there a newer release?

**Comment by fossfreedom** [comment]
@rodrigo-nogues v04.3 is required due to the changes in budgie-desktop 10.4

Please ask your AUR maintainer to update to the latest release.

https://github.com/cybre/budgie-screenshot-applet/releases

**Comment by rodrigo-nogues** [comment]
Great, thanks guys!
