### ISSUE TITLE
Segfault with the last version of budgie-desktop 10.4

### ISSUE THREAD

**Issue by Akaban** [cybre/budgie-screenshot-applet#34]
Hello,

There is an issue with **screenshot-applet** when used with the last version of budgie, indeed the budgie-panel just crash when I try to add the applet to my panel. Every package is up to date as I use Archlinux, it seems like this is a segfault with **libbudgie-plugin** but it recently occured with the update of budgie to 10.4. I will attach the log to this issue.

Best regards,

Akaban

[bug_screenshotapplet_logs.txt](https://github.com/cybre/budgie-screenshot-applet/files/1454520/bug_screenshotapplet_logs.txt)

**Comment by cybre** [comment]
Did you install the AUR package? If so, please reinstall from the git repo. The AUR package is not maintained by me and is outdated.

**Comment by Akaban** [comment]
Yes I did, I thought the package was up to date... How dumb of me I should have double checked before posting the issue ! Everything is solved, thanks ! And keep up the good work, I really like this plugin of yours :).

Best regards,

Akaban
