### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by baimafeima** [cybre/budgie-screenshot-applet#36]
When taking screenshots with `budgie-screenshot-applet` is there any chance that metadata may be present, especially when uploading this to imgur or any similar sites?

**Comment by cybre** [comment]
Can you please elaborate?

**Comment by baimafeima** [comment]
I was thinking of metadata such as timestamps/dates or screen resolution, etc. Surely, there must be timestamps which are added to the files and it would be great to be able to either modify that before uploading or even better, to have them automatically removed before clicking the upload button.
