### ISSUE TITLE
Paint/write on screenshot

### ISSUE THREAD

**Issue by bobblkabb** [cybre/budgie-screenshot-applet#39]
Deepin has a nifty screenshot tool where you can paint or write on the taken pic.
Doesn't have to be that sophisticated but simple drawing functions are very welcome.
I would also be happy if there was a simple way to jump and open directly to a picture app like gimp.

Or maybe, just maybe you might consider ditching the gnome screenshot for deepin screenshot :-)
[Deepin Screenshot Github](https://github.com/linuxdeepin/deepin-screenshot)

**Comment by cybre** [comment]
The applet does not use gnome-screenshot in any way.

**Comment by bobblkabb** [comment]
Alright, so whatever you use have a look at deepin screenshot. You can also blur and anonymize. 
They're quite busy.

**Comment by cybre** [comment]
I will not make the applet depend on an external tool. As for editing capabilities, I do not intend to add this feature currently. I will probably create a standalone screenshot utility for Budgie 11 with editing features.
