### ISSUE TITLE
screenshot but not to imgur

### ISSUE THREAD

**Issue by fossfreedom** [cybre/budgie-screenshot-applet#4]
does the applet always send to imgur first?

shouldnt the default be to just copy to the clipboard - and in the history (for example) have a checkbox to send to imgur.  

Key advantage - the default privacy is preserved for those that what to use a GUI screenshot util like this but dont want to send to imgur

BTW - I have a debian package of 0.3.1 ready to be published in a Ubuntu PPA - do you want me to hold off announcing this or are you happy for me to make it available to budgie-remix users?

**Comment by cybre** [comment]
Uploading from the history view would take too many steps (And I don't like that)
There is a "Local" option if you check the settings; it will save the screenshot to the disk without uploading it. It does add it to the history so I might add a way to upload it afterwards.

**Comment by cybre** [comment]
I just found a stupid mistake so I would wait for 0.3.2 if I were you.

**Comment by cybre** [comment]
Fixed in 8f93ea3

You can now upload screenshots taken with the "local" option directly from the history view.
"imgur" will continue being the default option.
![screenshot from 2016-07-01 10-35-28](https://cloud.githubusercontent.com/assets/3101505/16516303/aa815738-3f77-11e6-8da2-731c7f54f552.png)

Check it out if you want. I'll draft a new release as soon as you reply.

**Comment by fossfreedom** [comment]
ta - currently at work but will check tonight

Question - how do I change the out-of-the box default to take pictures local first - the user should then "opt-in" to sending to imgur via "settings" (?) (sorry I didnt find this local option when I had a quick look last night)

**Comment by cybre** [comment]
Open Raven > Settings > Panel > Select "Screenshot"  in the applet list > Click the gear icon in the bottom of the list > "Upload provider" combobox.

**Comment by fossfreedom** [comment]
sure - that's from a user point of view - good to know.

Where does this local option store its value to always be "local" 

I thought it would be in gsettings - https://github.com/cybre/screenshot-applet/blob/master/screenshot-applet/com.github.cybre.screenshot-applet.gschema.xml - didnt see this local option here.

**Comment by cybre** [comment]
It's the "provider" key

**Comment by fossfreedom** [comment]
k - thanks - value of "local".  cheers.  I'll patch this to be the default.
