### ISSUE TITLE
v0.3.2 -  local screenshot wants to upload

### ISSUE THREAD

**Issue by fossfreedom** [cybre/budgie-screenshot-applet#5]
![workspace 1_038](https://cloud.githubusercontent.com/assets/996240/16533275/73b23ef4-3fcf-11e6-8e41-55a7417d34f7.png)

I've got "local" set as the provider - after taking a screenshot I see the above.

No idea why it wants to upload - and there is nothing wrong with my internet connection ... I'm raising this issue with it :)

Any thoughts as to the issue?

**Comment by cybre** [comment]
Eh, this might also mean it can't open the file (I was lazy, I know :P).
Care to post some terminal output (budgie-panel) ?

**Comment by cybre** [comment]
oh wait. Check raven if "Local" is really the chosen option.
And if it is, try changing it to something else and back to Local.

**Comment by fossfreedom** [comment]
yep raven says "Local"

<pre>
budgie-panel --replace &
budgie-remix@budgieremix-eME732:~$ 
(budgie-panel:17322): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(budgie-panel:17322): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
** Message: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
** Message: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.
** (gnome-screenshot:17332): CRITICAL **: Unable to save the screenshot: Error opening file '/Screenshot from 2016-07-01 21-27-11.png': Permission denied
</pre>

Running gnome-screenshot in a terminal successfully writes a ~/Pictures screenshot picture

**Comment by cybre** [comment]
Also, which screenshot mode did you use when you got this error?

**Comment by cybre** [comment]
What is the output of `gsettings get org.gnome.gnome-screenshot last-save-directory` ?

**Comment by fossfreedom** [comment]
<pre>
gsettings get org.gnome.gnome-screenshot last-save-directory
''
</pre>

**Comment by cybre** [comment]
Huh, so it doesn't have a default one set.
Ok, I'll add an option to change the save directory instead of trying to use the last one used by gnome-screenshot.

Sigh... 0.3.3 it is :P

**Comment by cybre** [comment]
It'll just default to ~/Pictures or ~/Pictures/Screenshots

**Comment by fossfreedom** [comment]
k - thanks!

BTW - those people who don't use english as their locale is the folder known as "~/Pictures" ?

suspect need to grep through this file for the pictures folder name

<pre>
more .config/user-dirs.dirs 
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
</pre>

**Comment by fossfreedom** [comment]
... or use this command

xdg-user-dir PICTURES

**Comment by cybre** [comment]
Yeah, I'll use GLib.Environment

**Comment by cybre** [comment]
0.3.3 released.
Note: Local mode is now a boolean ("enable-local" in the gschema) so you'll need to update your patch.

**Comment by fossfreedom** [comment]
excellent thanks.  Looks good!
