### ISSUE TITLE
Can't make the softmare

### ISSUE THREAD

**Issue by Mackel123** [cybre/budgie-screenshot-applet#52]
Cannot convert from `GLib.HashTable<string,ScreenshotApplet.Backend.Providers.IProvider>' to `GLib.HashTable<string,weak ScreenshotApplet.Backend.Providers.IProvider>'

sysinfo :x86_64 Linux 5.0.4-arch1-1-ARCH

**Comment by fossfreedom** [comment]
This commit will fix this https://github.com/cybre/budgie-screenshot-applet/pull/54/commits/0e0c582adedc4105bb6677aa932e3ecc6ca35fc5

**Comment by cybre** [comment]
Thanks @fossfreedom
