### ISSUE TITLE
Broken in Budgie 10.5 (Arch)

### ISSUE THREAD

**Issue by mplx** [cybre/budgie-screenshot-applet#57]
Budgie 10.5 (Arch): applet disappeared in tray aswell as in panel (settings). Is still listed in "add applet" list however can't be added (no errors show in journal).

Can you have a look at this please? Thanks in advance! :)

**Comment by i2mo** [comment]
Same here

budgie-desktop 10.5.1 (git-10b814fa62bf774ca48e182548d3c6687a852314)
Arch (EndeavourOS) Kernel:  5.5.9-arch1-2 x86_64
Desktop: Gnome 3.36.0 
info: budgie-panel 
wm: budgie-wm 
dm: GDM 3.34.1, LightDM 1.30.0

**Comment by mplx** [comment]
As it's currently working I'll close this issue.
