### ISSUE TITLE
Feature Request: Ability to specify monitor

### ISSUE THREAD

**Issue by JoshStrobl** [cybre/budgie-screenshot-applet#6]
It would be really awesome to have the ability to specify a specific monitor to have a screenshot taken of, in the event an individual (_such as myself_) uses multiple monitors (_maybe don't provide the options if only a single monitor is detected_).

Thanks :heart:

**Comment by cybre** [comment]
This has been implemented. Thanks for the suggestion!

**Comment by fossfreedom** [comment]
@cybre will you creating a new release?  just wondering whether you are thinking of other stuff to be implemented before the next release.  Need to know whether to update the budgie-remix debian package or not.  

TIA.

**Comment by cybre** [comment]
@fossfreedom There will definitely be a new release soon. I'm still thinking about things to add or improve.
