### ISSUE TITLE
S/FTP Support

### ISSUE THREAD

**Issue by Seeder101** [cybre/budgie-screenshot-applet#7]
hi cybre, how are you? 
I'v a request...it's about uploading the captured photo throught a ftp-client to ftp-server 
you can look at similar feature with shutter this is the source code http://shutter-project.org/wp-content/uploads/releases/tars/shutter-0.93.1.tar.gz
this is the homepage http://shutter-project.org/
this software allowing me to upload to my own ftp server and provided a custom link url for the clipboard for example...through a webserver I install on the same vps/dedicated that providing the ftp-server

thank you...if you need any more details...let me know ;)

**Comment by cybre** [comment]
I will need something to test this with. Would you give me access to your FTP server?
Also, tell me how do you have it configured in shutter. (the values from the settings screen; uri, website url, ...).

**Comment by kherchel** [comment]
OP's not responding so here I am. I used a free website hosting service, here you go:
Host: mkwk012.cba.pl
Login: ftptest1
Password: ftptest123

It would be also very nice if, along with the FTP uploading, you added a function to randomize or at least add a random string to the end of the filename (so screenshot addresses couldn't be easily guessed by outsiders).

**Comment by cybre** [comment]
@kacperski1 Thanks! I already tested it with a free web host but it certainly helps to have multiple testing targets. I have the upload stuff working [(check it out :))](http://ftptest.cba.pl/screenshots/Screenshot%20from%202017-05-18%2010:24:56.png)
I just need to add the randomize bits.

**Comment by cybre** [comment]
FTP support is in :)

**Comment by Seeder101** [comment]
Hi guys...sorry....I wasn't use github for a while...
glad you found ftp server to test it with 
awesome @cybre ... and thanks for @kacperski1 to suggest a free-hosting service provider 
if you want to test out sftp I will contact you in IRC privately

**Comment by cybre** [comment]
Thanks @Seeder101. I already tested sftp.

**Comment by GendelfLugansk** [comment]
How to configure it to use sftp? If I put sftp:// in the beginning of uri, upload just doesn't work.
