### ISSUE TITLE
Delay does not work for selections 

### ISSUE THREAD

**Issue by theSoenke** [cybre/budgie-screenshot-applet#8]
The delay when taking screenshots of a selection currently seems not to work. It works for the screen and window mode, but when doing a selection it takes the screenshot immediately without the countdown. I'm using the latest version 0.3.8 on Solus.

But everything else works really great. Thanks for this applet :)

**Comment by cybre** [comment]
The applet wraps around gnome-screenshot at the moment. Delays on area screenshots don't work in gnome-screenshot so it's not something I can fix right now. I'll write my own backend eventually but for now it's not doable without resorting to nasty hacks.

**Comment by theSoenke** [comment]
Ok. Would be a useful feature. But then there is not much you can do about it now
